### ISSUE TITLE
use versioning to fetch data

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/csa-atrophy#2]
https://github.com/sct-pipeline/csa-atrophy/blob/21ae3759726163504798defe6eb7b46c46414ace/csa-fetch-dataset.sh#L34

at some point we will want to reference to a specific version of the openneuro database (e.g., say v0.4).

**Comment by PaulBautin** [comment]
Answer from neurostar:  [https://neurostars.org/t/openneuro-import-conditions/6940/2](url)
Obtaining specific subjects from the non-current version of the openneuro repository seems not possible. As these images are open, I suggest to download the test files on the "csa-atrophy" repository.

**Comment by jcohenadad** [comment]
ok, so a reasonable approach for now is to just specify the version, download everything, and select specific subjects when running the "testing" version of your pipeline.
