### ISSUE TITLE
Manual labelling correction

### ISSUE THREAD

**Issue by PaulBautin** [sct-pipeline/csa-atrophy#32]
When vertebral labelling works, each vertebra is labelled. However, manual correction of labelling currently uses spine-generic that requests user to manually input only 2 labels. How should i process labelling using the manual correction that contains only 2 labels?
Initial comment:
https://github.com/sct-pipeline/csa-atrophy/pull/31#issuecomment-670941179

**Comment by jcohenadad** [comment]
some clarifications to https://github.com/sct-pipeline/csa-atrophy/issues/32#issue-675624796:

reference to the code at the specific release used in the present codebase:

This line generates a mid-vertebral label at C2 and C5:
https://github.com/spine-generic/spine-generic/blob/v2.1.1/processing/process_data.sh#L67

i see those possibilities:
- only extract CSA at mid-level C3 (+/- X slices, to increase coverage and statistical power)
  - pros: no need to re-do labels
  - cons: CSA at C3 mid-level is not common
- register to the template using those two labels, warp the template (incl. vertebral levels) and then compute CSA at C2-C3
  - pros: CSA at C2-C3 is more common
  - cons: registration to the template is computationally heavy and could also introduce errors (could increase the variance of CSA across monte carlo simulations)
- create a manual label at disc C2-C3 and use it to compute CSA at this level +/- X slices
  - pros: no need for registration; common to extract CSA at these levels
  - cons: need to re-do a lot of manual labels (although part of it could be automatized, with ~15% failure)

For a first round of processing, i would suggest to go with the 1st approach. Then, we assess the results and discuss wether we want to keep that approach.

**Comment by PaulBautin** [comment]
Thanks for your comments. 

-With the first option the corrected data results will not be in sync with the rest of the data which is labelled and segmented from C2 to C5. This would mean that we cannot compute the same statistics with the corrected data and the data that worked the first time around. If we choose this option, i think we should have all data showing the same results (C3 +/- X slices). How many slices would that be? Should we resample data (same image quality)? The wider the range, the less we can ensure that we are measuring the same thing in different images.

-The second option seems to be the closest to what we already do but is costly in time and error. Would these errors be template dependent? Would we use PAM50 template?

-The third option would simply be a second try for the automated labelling?

**Comment by jcohenadad** [comment]
> With the first option the corrected data results will not be in sync with the rest of the data which is labelled and segmented from C2 to C5.

what "rest of the data" are you referring to? can you pls point to a URL

**Comment by PaulBautin** [comment]
> what "rest of the data" are you referring to?

The images for which the automatic C2-C3 detection worked.

I would like to be clear on this. My understanding is that in this pipeline the dataset is processed a first time with a C2-C3 automatic detection with steps:
- 1) automatic C2-C3 detection
- 2) Spinal cord is straightened with a warping field.
- 3) Other disks or vertebrae are found and labelled using a template (PAM50)
- 4) Warping field is "inversed" (brought back to the original image with labels)
- 5) CSA is measured on each vertebra from C2 to C5

In the results of the automatic process, there are errors that must be corrected:
- With method 1 we create a manual label on mid-level C3 vertebrae and measure CSA on X slices on top and underneath. 
- With method 2 we continue using the spine generic labels and we apply steps 2,3,4 and 5 of the automatic process
- With method 3 we create a manual label at C2-C3 disk and measure CSA on X slices on top and underneath. How do we know where the boundaries of C2 and C3 are?

In the original process (currently last commit) https://github.com/sct-pipeline/csa-atrophy/tree/8ce5711f38eec92ce6492035ce02d51236c7c9d7 with file manual_labeling_correction.sh users were asked to manually input all disks from on top C2 to underneath C5. The process worked but file organization needed to be corrected and it seemed better to call spine-generic in the code than copy/paste files such as https://github.com/spine-generic/spine-generic/blob/master/spinegeneric/cli/populate_derivatives.py. 
So either we go for: original method, method 1 or method 3; and implement spine generic derivatives organisation script or we keep spine-generic two label manual processing and apply method 2 (as in https://github.com/spine-generic/spine-generic/blob/v2.1.1/processing/process_data.sh#L67)

**Comment by jcohenadad** [comment]
> With method 2 we continue using the spine generic labels and we apply steps 2,3,4 and 5 of the automatic process

no, with method 2:
- register to the template using those two labels
- warp PAM50 to subject
- compute CSA using the PAM50's vertebral level info

so, with method 2, there is no step 2-5

> With method 3 we create a manual label at C2-C3 disk and measure CSA on X slices on top and underneath. How do we know where the boundaries of C2 and C3 are?

we don't. That's a cons. Moreover, i was just thinking that for images that are rotated (data augmentation), the X slices above/below will not have the same coverage. So we should probably forget about this approach.

maybe a better approach would be to:
- have a first pass where all subjects are processed, including vertebral labeling
- in cases where vertebral labeling fails, ask to do it manually (all discs, not only 3 and 5 mid-levels)
  - in this case, generate a labeled segmentation from the labeled discs
- then, a second pass, which includes data augmentation: in this case, the labeled segmentation will experience the same transformation. That way, we don't have to deal with labeling for the transformed data, and we can focus on CSA computation only.

**Comment by PaulBautin** [comment]
Ok, it seems like the best solution for now. This is priority, i will soon open a PR for this issue. 
It will contain tweaked code from spine-generic. I find that annoying because i can see a program like spine-generic becoming a reference for SCT dataset organization/correction/convention (does it already exist?).

> It would really help if you could make a schematic of the workflow

I agree, SCT often has cool schematics. Is there a particular program that the team uses?

**Comment by jcohenadad** [comment]
> Is there a particular program that the team uses?

apple keynote or microsoft PPT
