### ISSUE TITLE
error labelling

### ISSUE THREAD

**Issue by PaulBautin** [sct-pipeline/csa-atrophy#47]
@jcohenadad, C2-C3 automatic detection fails for about 4 out of 20 subjects and labelling is off for 4 out of 5 subjects in QC. Should i test another dilation factor?

Current process:
~~~
# dilate segmentation (for cropping)
sct_maths -i ${file_seg}.nii.gz -dilate 15 -shape cube -o ${file_seg}_dil.nii.gz
# crop image
sct_crop_image -i ${file}.nii.gz -m `${file_seg}_dil.nii.gz`
~~~

QC:
![sub-cardiff05_T1w_RPIr_crop](https://user-images.githubusercontent.com/49245398/90572400-eeb39a00-e181-11ea-9c60-d81fb48eeacd.png)
![sub-unf03_T1w_RPIr_crop](https://user-images.githubusercontent.com/49245398/90572407-f2472100-e181-11ea-842e-ea229b7e5f3c.png)

**Comment by jcohenadad** [comment]
> Should i test another dilation factor?

ah! maybe what we should do is simply do the crop _after_ the vertebral labeling. That way, we can also benefit from the manual correction already produced in the derivatives/

**Comment by PaulBautin** [comment]
That works!
