### ISSUE TITLE
implement random transformation 

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/csa-atrophy#5]
to mimic subject repositioning, for each rescaling, it would be nice to have a random translation and rotation of the image.

a suggestion is to generate randomized transfo per subject, and freeze them in the repos, so that we can reproduce the results by inputting the frozen params in subsequent runs of the pipeline

**Comment by PaulBautin** [comment]
Hi, i am unsure on how to proceed with this step. 
- Should i loop through slices applying scipy, numpy rotation?
- "sct_course_london20" presents warping fields. How do i create these? 
- When using nibabel there is a function "affine", is it possible to modify the resulting matrix to obtain a transformation?

**Comment by jcohenadad** [comment]
good question. For the rotation I would suggest following [this code](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/testing/create_test_data.py#L166) (note the padding on line 161). For translation, you will probably find something in `skimage.transform`, otherwise you can play with numpy matrix indices.
