### ISSUE TITLE
Underestimated CSA measures on T1w images after rescaling

### ISSUE THREAD

**Issue by PaulBautin** [sct-pipeline/csa-atrophy#69]
As we can see in the following boxplot, CSA measures after rescaling are underestimated. A plausible explanation is that most manual segmentations (when there is an obvious error in the segmentation for rescaling = 1 only) overestimate the CSA compared to the non-manual segmentations. 
(What i called a missing slice is actually a missing CSA values on a slice.)

We cannot use manual segmentation for rescale = 1 and not use manual segmentation for the other rescalings. Solutions are:
- Discard subjects with a missing CSA value. cons: It's too bad to discard complete subjects for a few missing slices,
- Always use the automated (non-manual) segmentation, except in input of the labeling. cons: Could cause incoherence between segmentation and segmentation_labeled during sct_process_segmentation? (This is currently what we do for all rescalings other than rescale = 1)
- Interpolation: If there is a missing vertebrae level value for a slice in the segmentated_labeled image we can interpolate its value. When there is a missing CSA value in the segmentation, `sct_process_segmentation` outputs: "No properties for slice X" i thought a CSA measure value was attributed to the slice X but I'm not sure?

![fig_boxplot_atrophy](https://user-images.githubusercontent.com/49245398/92074183-6dfcbc80-ed83-11ea-8a4c-ce4c5a8f37e1.png)

commit: https://github.com/sct-pipeline/csa-atrophy/pull/67/commits/b214290cde8c2b7e36575ae9d5c618076186e116

**Comment by jcohenadad** [comment]
> A plausible explanation is that most manual segmentations (when there is an obvious error in the segmentation for rescaling = 1 only) overestimate the CSA compared to the non-manual segmentations.

how many manual segs are we talking about? If only 5 out of 216 subjects, this is likely not the problem. If it's more 200 out of 216, then yes, this is a possible explanation.

> Always use the automated (non-manual) segmentation, except in input of the labeling. cons: Could cause incoherence between segmentation and segmentation_labeled during sct_process_segmentation? (This is currently what we do for all rescalings other than rescale = 1)

no, it will not cause any incoherence. That's the next thing to try.

**Comment by PaulBautin** [comment]
As mentioned here: https://github.com/sct-pipeline/csa-atrophy/issues/71#issuecomment-690279831, results for T2w images now look good and i have noticed no errors. Should we re-run a process for T1w images (making sure that error was not in process)?

**Comment by PaulBautin** [comment]
I have recently re-run process for T1w images and results are almost identical... @jcohenadad any idea?

**Comment by jcohenadad** [comment]
there are a couple of suspicious things:
- the 100% should show a dispersion, because not all values in the monte carlo simulation should have exactly the same CSA
- the previous point makes me skeptical about the fact that maybe, the non-100% rescale values are compared to a single 100% rescale value (instead of a the mean across monte carlo simulation for the 100% rescale case).

**Comment by PaulBautin** [comment]
`df_sub['rescale_estimated'] = df_sub['mean'].div(df_sub['csa_without_rescale'])`
This ^ is the formula implemented in the code to compute `rescale estimated`.

By construction, i think that it is normal for the 100% rescale to have no dispersion:
If rX = 1 (100% rescale) the formula becomes:
rescale_estimated_subject = MEAN[ CSA(sI, 1, :) ] / (MEAN[ CSA(sI, 1, :) ]) = 1

What is surprising to me is the number of outliers (often overestimated CSA), as if the transformation had a much more important effect on T1w images than T2w images.

**Comment by jcohenadad** [comment]
I'm not sure i fully understand the argument in https://github.com/sct-pipeline/csa-atrophy/issues/69#issuecomment-698059064, but my argument is that, given monte carlo i and rescaling rX, the estimated rescaling is expressed as:
~~~
rescale_estimated(i, rX) = CSA(i, rX) / MEAN[CSA(i, rX)]
~~~

So, if you consider a single monte carlo sample for rX=1, the value of a _single_ sample is not necessarily equal to the average of its distribution.

**Comment by PaulBautin** [comment]
I agree with your comment https://github.com/sct-pipeline/csa-atrophy/issues/69#issuecomment-698065018:
"if you consider a single monte carlo sample for rX=1, the value of a single sample is not necessarily equal to the average of its distribution."

` rescale_estimated(i, rX) = CSA(i, rX) / MEAN[CSA(i, rX)]`
The results of the formula ^ for T1w images.
![fig_boxplot_atrophy](https://user-images.githubusercontent.com/49245398/94170685-5b474600-fe5e-11ea-8cc7-9d3b26fdf6db.png)

However, this graph accumulates inter-subject and transformation variabilities. My intention with `rescale_estimated(i, rX)` was to only show the variability due to transformations (independently of the intersubject variabilty). Because we have already shown intersubject variablilty in this graph:
![fig_boxplot_csa](https://user-images.githubusercontent.com/49245398/94170572-3d79e100-fe5e-11ea-898b-f0ce72927f27.png)
We can almost see that CSA values for rescale 100% are slightly higher than the rest.
Not sure if this is clearer..

**Comment by jcohenadad** [comment]
@PaulBautin you make a valid point about the inter-subject variability. And regardless, even if you include inter-subject variability, there is still an offset with the rescale results for T1.   This is puzzling 🤷‍♂️

note: it would really help if you could plot with the same x and y scaling (ie: having the bissection with 45° angle).

**Comment by PaulBautin** [comment]
This issue can be closed because CSAs are no longer underestimated since merge of PR #82.
