### ISSUE TITLE
Improvement in CSA measures with T2w images

### ISSUE THREAD

**Issue by PaulBautin** [sct-pipeline/csa-atrophy#71]
I have noticed with the following figure that results with T2w images are closer to what we expected. Should we try to run process on T2w images? Any idea why changing the contrast changes results?
(Edit: i only have T2w manual labeled images in my data-multi-subject local dataset)

![fig_boxplot_atrophy](https://user-images.githubusercontent.com/49245398/92248713-1780a280-ee97-11ea-90d2-748c30c2910f.png)

**Comment by jcohenadad** [comment]
nice!

> Edit: i only have T2w manual labeled images in my data-multi-subject local dataset

both T1w and T2w are available on the git-annex repos since this PR: https://github.com/spine-generic/data-multi-subject/pull/15

**Comment by jcohenadad** [comment]
but: the argument about _not_ using the manual segs for the rescale=1 still holds (so i would fix that before launching with T2w)

**Comment by PaulBautin** [comment]
I have the results and they look good!
![fig_boxplot_atrophy](https://user-images.githubusercontent.com/49245398/92397516-ebfaf380-f0f4-11ea-9e06-81d26a48e54f.png)

**Concerns:**
- Error seems to increase with increasing rescalings
![image](https://user-images.githubusercontent.com/49245398/92397725-501db780-f0f5-11ea-9b5d-17506d022d94.png)

- I had to drop a certain number of dataframe rows(about 600 out of 187200), the problem seems a little different than https://github.com/neuropoly/spinalcordtoolbox/issues/2864. Still investigating.

**Comment by jcohenadad** [comment]
Fantastic news @PaulBautin !!!🏅 

> I had to drop a certain number of dataframe rows(about 600 out of 187200), the problem seems a little different than neuropoly/spinalcordtoolbox#2864.

why did you have to? could you document the error you are experiencing?

> Why did T1w images have underestimated csa after rescaling? Still investigating.

indeed, this is puzzling 🤔

**Comment by PaulBautin** [comment]
Closing Issue: I've tested https://github.com/sct-pipeline/csa-atrophy/commit/dfb4801b05877b5eeebb1a3f314ead32eed6a2b5 on Compute Canada and results are in line with what we found last time (without having to drop any dataframe rows).
