### ISSUE TITLE
Error: resampling of disk labels fails

### ISSUE THREAD

**Issue by PaulBautin** [sct-pipeline/csa-atrophy#74]
In last results certain subjects (notably sub-brnoUhb*) have disk-labels with non-int values. Example:  [sub-brnoUhb02_T2w_labels-disc-manual_RPI_r.zip](https://github.com/sct-pipeline/csa-atrophy/files/5184061/sub-brnoUhb02_T2w_labels-disc-manual_RPI_r.zip)
The function `sct_resample` uses by default a linear resampling that is not adequate for these labels. A solution is to use an interpolation to nn (nearest neighbour).  However, labels seem to be missing on output images.

**test:**
command: `sct_resample -i sub-brnoUhb02_T2w_labels-disc-manual.nii.gz -mm 0.8x0.8x0.8 -x nn -o test.nii.gz`
file: [sub-brnoUhb02_T2w_labels-disc-manual.zip](https://github.com/sct-pipeline/csa-atrophy/files/5184057/sub-brnoUhb02_T2w_labels-disc-manual.zip)
result image: [test.zip](https://github.com/sct-pipeline/csa-atrophy/files/5184071/test.zip)

**Comment by jcohenadad** [comment]
this behaviour was expected, see https://github.com/sct-pipeline/csa-atrophy/issues/59#issuecomment-683036793

one workaround is to dilate the labels, (eg sct_math -dilate 3) and then resample with NN.
