### ISSUE TITLE
Add graph showing intra-subject variability (STD) as a function of atrophy estimation error 

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/csa-atrophy#86]
Once the graph is done, we should identify the 5-10 subjects with worse STD, and see if they are associated with strong movements/artifacts.

If that's the case, it should be reported as a new finding in the manuscript.

**Comment by PaulBautin** [comment]
## Graph without removing any subjects
The first graph shows COV in function of error % without removing any subjects. 
![fig_err_in_function_of_std](https://user-images.githubusercontent.com/49245398/97089042-07698180-1603-11eb-8829-a6f7dd643a4d.png)

The 2nd graph shows that T1w and T2w outliers seem not correlated. Subjects in red are the worst outliers of T1w images and subjects in green are the worst outliers of T2w images.
![Screenshot from 2020-10-24 15-16-41](https://user-images.githubusercontent.com/49245398/97091726-f8d39800-160b-11eb-895d-5ac20b21ce8f.png)


## After removing subjects
Presently if CSA is not computed the vertebrae levels are removed from the dataframe. It looks like the segmentation on images with missing CSA does not cover C3-C5 cord, this could be related to image transformation. We could try to re-integrate padding to see if it resolves this issue. example:
Cropped and transformed image:
[sub-barcelona04_T1w_RPI_r_crop_r0.98_t1.zip](https://github.com/sct-pipeline/csa-atrophy/files/5433528/sub-barcelona04_T1w_RPI_r_crop_r0.98_t1.zip)
segmentation of ^ image
[sub-barcelona04_T1w_RPI_r_crop_r0.98_t1_seg.zip](https://github.com/sct-pipeline/csa-atrophy/files/5433529/sub-barcelona04_T1w_RPI_r_crop_r0.98_t1_seg.zip)

In the following graph all  subjects with a missing CSA were removed (not only the vertebra level). It seems to eliminate values with high COV and low error % improving the correlation between both metrics.

![fig_err_in_function_of_std_without_error](https://user-images.githubusercontent.com/49245398/97089245-87dcb200-1604-11eb-9e60-295a4d25f826.png)

In this last graph, i tried to identify outlier subjects and looked at their image quality. It is difficult to affirm that these are the worst images, but it is obvious that if the subject is an outlier for one rescaling it has good chances to be an outlier for the other rescalings. :
![fig_err_in_function_of_std](https://user-images.githubusercontent.com/49245398/97091295-f885cd80-1608-11eb-8480-794ab91ba775.png)

**Comment by jcohenadad** [comment]
Very cool investigations @PaulBautin ! Too bad these results don't follow our intuitions (about the correlation). Could you open a PR so I can look at the code?

**Comment by PaulBautin** [comment]
@jcohenadad. The merge of PR #89, has not modified the results and the number of outliers. No correlation between COV and percentage can be deduced.
Used repo for t1: https://github.com/PaulBautin/csa-atrophy/tree/compute_canada
Used repo for t2: https://github.com/sct-pipeline/csa-atrophy

![Screenshot from 2020-11-04 16-28-49](https://user-images.githubusercontent.com/49245398/98169788-e898a400-1eba-11eb-8806-2f1dc0888a5f.png)

**Comment by jcohenadad** [comment]
thank you for looking into it @PaulBautin , but as a sanity check i'd still like to see a side-by-side results comparison as mentioned in https://github.com/sct-pipeline/csa-atrophy/issues/83#issuecomment-721986071

**Comment by PaulBautin** [comment]
As predicted with PR #89 eliminates values with very high COV:

repo for results before #89: https://github.com/sct-pipeline/csa-atrophy/tree/stat_cov_err
repo for results after #89: https://github.com/PaulBautin/csa-atrophy/tree/compute_canada

![Screenshot from 2020-11-04 17-21-02](https://user-images.githubusercontent.com/49245398/98174151-657b4c00-1ec2-11eb-9912-d30ce0c5e7bf.png)

**Comment by jcohenadad** [comment]
it's reinsuring. Even though there are still effects that we don't fully understand (the offset for T1w), we can trust these results better, now that the bug with the crop is fixed. I think we can move forward with the article.
