### ISSUE TITLE
Resampling images to 0.5 mm isotropic

### ISSUE THREAD

**Issue by PaulBautin** [sct-pipeline/csa-atrophy#93]
During the last meeting, we discussed resampling images to 0.5 mm isotropic. Even though, no additional information is added to the image, hypothesis was that, a finer resampling could increase the precision of transformations that use interpolation. Moreover, the 0.5 mm isotropic resampling was chosen to ensure that the systematic resampling (0.5 mm isotropic) performed by Deepseg did not affect image quality and segmentation.

**Comment by PaulBautin** [comment]
Results for T2w images using:
config for 0.5 mm: [config_script_0.5mm.zip](https://github.com/sct-pipeline/csa-atrophy/files/5567803/config_script_0.5mm.zip)
config without resampling: [config_script_t2.zip](https://github.com/sct-pipeline/csa-atrophy/files/5567809/config_script_t2.zip)
last commit used: https://github.com/sct-pipeline/csa-atrophy/commit/1eb258ebbd47c7fbb91c5cfa93529d04db31212e

No improvements are visible with image resampling to 0.5 mm iso. There even seems to be an increase in missing vertebrae on resampled images segmentation: 
![Screenshot from 2020-11-19 10-29-27](https://user-images.githubusercontent.com/49245398/99687558-cd00d200-2a52-11eb-9e9b-bcb7623e1cc7.png)

example of missing vertebrae in segmentation (i will look more into this issue): 
[sub-tokyoIngenia02_T2w_RPI_r_r0.97_t22_crop.zip](https://github.com/sct-pipeline/csa-atrophy/files/5567850/sub-tokyoIngenia02_T2w_RPI_r_r0.97_t22_crop.zip)
[sub-tokyoIngenia02_T2w_RPI_r_r0.97_t22_crop_seg.zip](https://github.com/sct-pipeline/csa-atrophy/files/5567851/sub-tokyoIngenia02_T2w_RPI_r_r0.97_t22_crop_seg.zip)

**Comment by jcohenadad** [comment]
The problem of bad segmentation (ie that stops in the middle of the FOV) is caused by a failure in the centerline detection:
![image](https://user-images.githubusercontent.com/2482071/99816265-6e525b80-2b19-11eb-898c-de6d8014b414.png)

This is likely caused by the FOV being too small (ie: the trained model does not recognize such small FOV).

**Comment by PaulBautin** [comment]
Still no improvements are visible with image resampling to 0.5 mm iso. However the centerline issue https://github.com/sct-pipeline/csa-atrophy/issues/93#issuecomment-731229356 seems to be resolved with PR #94.
commit: https://github.com/sct-pipeline/csa-atrophy/pull/94/commits/ad90b20b3514bc11c6d23bb2ba01b8c649dbabdd
config: [config_script_0.5mm.zip](https://github.com/sct-pipeline/csa-atrophy/files/5586853/config_script_0.5mm.zip)

![Screenshot from 2020-11-23 20-38-07](https://user-images.githubusercontent.com/49245398/100035432-2e66cf00-2dcc-11eb-8f4c-f1d34cd952ac.png)

**Comment by jcohenadad** [comment]
hum, these overestimations at 0.5mm are suspicious. i’d like to dig to understand what could explain those results

**Comment by jcohenadad** [comment]
@PaulBautin it also seems like after the fix (ad90b20), there is a slight overestimation on the 0.8mm iso plot compared to the results before the fix. The scaling of the plot is not the same, so it is difficult to assess precisely though.

Regarding the overestimation at 0.5mm, I would like to understand what's going on. Could you please share a representative subject (ie: with the over-segmentation at 0.5mm and not at 0.8mm). If too large, you can put the data on the cloud somewhere, or via duke (or let me know where they are on compute canada).
